version : "3.1"
services:
  nats:
    container_name: nats
    image: nats
    ports:
      - 4222:4222 # for clients
      - 8222:8222 # HTTP management port for reporting
      - 6222:6222 # routing port for clustering
  rqlite:
    container_name: rqlite
    image: rqlite/rqlite
    ports:
      - 4001:4001
      - 4002:4002
  mormon-ui:
    container_name: mormon-ui
    image: angadsharma1016/mormon-ui
    ports:
      - 80:8080
    restart: on_failure